name: Documentation

on: [push]

jobs:
  web:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build documentation
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-sphinx
        cd web/
        make html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: web/_build/html
        single-commit: true
        clean: true
        clean-exclude: CNAME
